// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1t0y_RmWoSc7YSCPPmP4ItRV6IiCs_Ek',
    appId: '1:605953345089:web:d03b58892a0e71267128c0',
    messagingSenderId: '605953345089',
    projectId: 'flutter-seeder',
    authDomain: 'flutter-seeder.firebaseapp.com',
    storageBucket: 'flutter-seeder.appspot.com',
    measurementId: 'G-S921XEMS89',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-ILIYenW7zbzDiV3EPbafuCT0vxavlQM',
    appId: '1:605953345089:android:34440600ee538c757128c0',
    messagingSenderId: '605953345089',
    projectId: 'flutter-seeder',
    storageBucket: 'flutter-seeder.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9NC_c8kyKT9duxKKTFHSmU7kfpnTGwyg',
    appId: '1:605953345089:ios:3ee44aef9ed239be7128c0',
    messagingSenderId: '605953345089',
    projectId: 'flutter-seeder',
    storageBucket: 'flutter-seeder.appspot.com',
    iosClientId:
        '605953345089-scldlgs4fahbt9g5sfcriv5vbi5v1582.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterSeed',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9NC_c8kyKT9duxKKTFHSmU7kfpnTGwyg',
    appId: '1:605953345089:ios:3ee44aef9ed239be7128c0',
    messagingSenderId: '605953345089',
    projectId: 'flutter-seeder',
    storageBucket: 'flutter-seeder.appspot.com',
    iosClientId:
        '605953345089-scldlgs4fahbt9g5sfcriv5vbi5v1582.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterSeed',
  );
}
